### ISSUE TITLE
Feedback V2.0

### ISSUE THREAD

**Issue by clfnk** [iam-ictm/eCH-0170#1]
**Anwendbarkeit**
V2.0, Allgemein.
Beschreiben, wie der Standard angewendet werden soll: Nur zur konzeptuellen Bewertung eines Systems oder bildet der Standard die Grundlage zur Zertifizierung, bei der auch geprüft wird, ob die Kriterien korrekt umgesetzt sind (was im Krypto-Bereich nicht ganz einfach ist)?
 
**Definition Credential**
V2.0, Kapitel 3.9.
Definition von Credential allenfalls umformulieren / erweitern, da aktuell noch schwierig zu verstehen. Da wichtiger Begriff der vorbelastet ist (landläufig verstanden als "Username/Passwort"), ist eine verständliche Definition zentral.
 
**Korrektur: Überbringer -> Subjekt**
V2.0, Kapitel 5.1.2, Tabelle 3, Zeile 3, Spalte 2: 
[..] vorliegende Authentifizierungsbestätigung für Subjekt [...] (statt Überbringer)
 
**Bemerkungen zu Authentisierungsmittel**
V2.0, Kapitel 6.1.1 (sowie Kapitel 9.6, 9.7). Fragen.
Schutz vor Duplikation: Unterscheidung zwischen Schutz vor Duplikation durch Hersteller/Herausgeber (bzw. vor Übergabe) und Dritten (bzw. nach Übergabe)?

Verfügbarkeit: Ist die Verfügbarkeit (bzw. Potential für Denial of Service / bzw. die Ersetzbarkeit des Mittels) nicht auch eine wichtige Frage? Schadenspotential durch Nichtverfügbarkeit (Verfügbarkeit ist üblicherweise eine Sicherheitseigenschaft)? 

Revozierbarkeit: Ist die Revozierbarkeit nicht auch eine wichtige Frage? Wie schnell kann der Benutzer ein gestohlenes / verlorenes Authentisierungsmittel melden / zurückziehen lassen? Wie sicher ist der Prozess (vs. Verfügbarkeit).
 
Bemerkung: In der Beschreibung des Mittel im Anhang, 9.7, sollte ggf. auf den unterschied der sicheren Schlüsselablage (Schlüssel nicht zwingend auf dem Device selbst erzeugt sondern allenfalls importiert) und der sicheren Schlüsselerzeugung (Schlüssel auf dem Device erzeugt, es kann kein Backup geben) aufgreifen.

Bemerkung: In der Beschreibung der Devices in 9.6 und 9.7 ggf. konkrete Beispiele machen. Für mich ist ein Computer mit einer Festplatte (SSD Flash Speicher) und einem darauf abgelegten Schlüssel auch ein physisches Device und entspricht konzeptuell einer SmartCard mit CPU und Festplatte (Flash) mit Schlüssel darauf.

**Bemerkungen zu Authentizität der Authentifizierungsbestätigung**
V2.0, Kapitel 6.2.1.
Aktuell: [...] Die Authentizität kann mit Hilfe einer Digitalen Signatur bewiesen werden [...]
Vorschlag: [...] Die Authentizität kann beispielsweise mit Hilfe einer Digitalen Signatur bewiesen werden [...] 

Flexibilität: Gibt es allenfalls "Zusatzpunkte" für ein System, welches eine 2te, Alternativvariante implementiert die Mathematisch unterschiedlich zum Hauptverfahren ist, so dass im Fall einer Cryptoattacke auf das Hauptverfahren das Alternativverfahren zur Anwendung kommen kann?

Hinweis: Die Digitale Signatur ist üblicherweise als asymmetrisches Verfahren definiert. Integritätssicherung mittels (H)MAC wird da nicht dazugezählt. Dies in der Tabelle allenfalls korrigieren. Es ist auch zu beachten, dass je nach Art der verwendeten Verschlüsselung der Integritätsschutz / die Authentisierung der Nachricht mit abgedeckt ist (Stufe 1a).
 
Hinweis: Bezüglich konkreten Verfahren eine Aussage machen, z.B. dass diese nicht Gegenstand des Dokuments sind oder dass dazu ein häufiger aktualisierter Anhang erstellt wird oder dass im Dokument eine andere Quelle referenziert wird. Wichtige Punkte sind erlaubte Algorithmen (Hash und Signatur), Schlüssellängen und insbesondere auch die Qualität der Zufallszahlen (Echte vs. Pseudo-Random, Entropie-Seeding). Es sollte auch eine Aussage zur Verwaltung  der Schlüssel (Erzeugen, Speicherung in Hardware vs. Software) gemacht werden. In Hardware gespeicherte symmetrische Schlüssel mit Verwendung eines sicheren symmetrischen Verfahrens können allenfalls besser sein, als in Software gespeicherte private Schlüssel (in Kombination mit einem niederwertigen Verfahren) zur asymmetrischen Signatur. Hier ist das Bilden der Stufen aus meiner Sicht nicht ganz so einfach wie gezeigt.

Hinweis: Bei 1a (Symmetrische Signatur) gehe ich davon aus, dass jeder RP einen eigenen Schlüssel vom IdP bekommt / verwendet. Ist ggf. zu ergänzen.
 
**Bemerkungen zu Verschlüsselung der Authentifizierungsbestätigung**
V2.0, Kapitel 6.2.2.
Es gelten im Prinzip dieselben Aussagen wie für Kapitel 6.2.1. Es ist zu beachten, dass die Verschlüsselung des Payload nicht direkt bzw. nur mit dem Public Key des RP geschieht sondern dass intern symmetrisch verschlüsselt wird und der symmetrische Schlüssel per "Key-Wrapping" asymmetrisch gesichert transportiert wird. So spielt auch hier die Qualität der Zufallszahlen (symmetrische Schlüssel, Initialisierungsvektoren), die Algorithmen sowie jeweiligen Schlüssellängen  wichtige Rollen für die Güte.
 
**Bemerkungen zu Übermittlungsform der Authentifizierungsbestätigung**
V2.0, Kapitel 6.2.3.
Gibt es hier nicht eine Wechselwirkung zur Verschlüsselung / Integritätssicherung? Wenn indirekte Übermittlung verwendet wird, muss die Referenz dann verschlüsselt werden oder genügt Integritätsschutz? Ist die Verschlüsselung des Kanals bei indirekter Übertragung genügend oder ist dies eine Stufe zwischen "Keine Verschlüsselung" und "(Payload) Verschlüsselung"? Ist bei der indirekten Übermittlung eine Umsetzung mit "Payload-Verschlüsselung" und gleichzeitiger "Transport-Verschlüsselung" besser als "nur" mit Payload-Verschlüsselung? Gibt es für die Authentisierung des RP beim IdP „Zusatzpunkte“ bzw. gibt es da Anforderungen an die Authentisierung (Username/Password vs. zertifikatsbasiert vs. keine Authentisierung wenn Payload verschlüsselt)? 
 
**Bemerkungen zu Verknüpfung natürliche und juristische Personen**
V2.0, Kapitel 6.3.4, Fragen.
Zusätzliche Frage: Was ist die zeitliche Gültigkeit der Verknüpfung?
Hinweis: Wie wird Deprovisionierung bzw. Neuprüfung gemacht bzw. gibt es da Anforderungen? Die Berechtigungen / gültigen Verknüpfungen können ändern. Ist die juristische Person zuständig, Änderungen zu melden? Wer darf das? Oder wird die Verknüpfung alle X Tage neu geprüft?
 
**Bemerkungen Revokation / Deprovisionierung**
V2.0, Allgemein.
Sollte allenfalls (z.B. in Kapitel 6.3.6) auch auf die Revozierbarkeit / Deprovisionierung des Authentisierungsmittels / des Subjekt-Kontos eingegangen werden? Wie wirken sich verschiedene Ansätze und Bereitstellungszeiten (Mail vs. Hotline, Bürozeiten vs. 24x7, innerhalb X Minuten revoziert) auf die Einstufung aus?

**Comment by AnnettLaube** [comment]
In der Version 0.6 des Standards eCH-0170 V2.0 wurden die folgenden Punkte behandelt:

- Definition **Credential**: neu Tabelle mit Beispiele bei Authentifizierungsmittel Kap. 3.6
- Korrektur: **Überbringer** -> Subjekt: Neue Rolle von Subjekt und entspr. Anpassungen im Dokument
- Bemerkungen zu **Authentizität der Authentifizierungsbestätigung**: Kriterium wurde entspr. angepasst (nur noch 2 Stufen)
- Bemerkungen zu **Verschlüsselung der Authentifizierungsbestätigung**: Fussnote hinzugefügt

Die anderen Punkte werden in den nächsten Versionen des Standards behandelt.

Zu Punkt: **Übermittlungsform der Authentifizierungsbestätigung**
- ja, es gibt eine Verbindung  Verschlüsselung / Integritätssicherung. Wenn indirekt übertragen wird, kann man verschlüsseln, ober es bringt keine "Pluspunkte".
- Der Kanal mit immer transportgesichert werden, deshalb jetzt neu die Vorbedingungen an das Gesamt-IAM-System in Kap. 6.1. Dasselbe gilt for die Authentifizierung der RP.

Danke für den wertvollen Input und schöne Grüsse,
Annett

**Comment by AnnettLaube** [comment]
In der Version 0.7 des Standards eCH-0170 V2.0 wurden die folgenden Punkte behandelt:

**Bemerkungen zu Authentisierungsmittel**
Schutz vor Duplikation: gehört zu Kriterium Zertifizierung Kap. 6.2.2
ebenso Schlüsselablage
(die Festplatte mit Schlüssel lässt sich sicher nicht FIPS 140 Level 3 zertifizieren.)

Verfügbarkeit und Revozierbarkeit sind wichtig, aber gehören nicht direkt zum Prozess Authentifizierung und müssen daher innerhalb der Steuerungsprozesse festgelegt werden (siehe Kap. 5.3.3)
Genauso die Punkte: **Revokation / Depovisionierung**

**Comment by AnnettLaube** [comment]
In der Version 0.8 des Standards eCH-0170 V2.0 wird/wurden die folgenden Punkte behandelt:

**Anwendbarkeit**
Hinweis, dass der Standard ein Ausgangspunkt der Zertifizierung sein sollte wurde in die Zusammenfassung und Kap. 2.2 aufgenommen
Abschliessende Diskussion in der nächsten FG Sitzung

**Bemerkungen zu Verknüpfung natürliche und juristische Personen**
diese Verknüpfung wird laut eIdas entsp. den auf nationaler Ebene anerkannten Verfahren geregelt. Daher Aufnahme des Punktes in Kap. 6.4.4 und Kap. 5.3.3
