### ISSUE TITLE
Inhaltliches Feedback

### ISSUE THREAD

**Issue by rbuff** [iam-ictm/eCH-0170#2]
**Services sind ebenfalls Subjekte:**
Die Zusammenfassung erwähnt als Subjekte explizit natürliche und juristische Personen. Gemäss Definition Subjekt (Kpt. 3.18) sind Services auch zu berücksichtigen. Ist mein Eindruck korrekt, dass bei diesem Qualitätsmodell diese nicht berücksichtigt wurden? Falls ja: Ich fände es sinnvoll, wenn explizit erwähnt werden würde, dass diese ausgeklammert wurden, aus welchen Gründen und (ev. im Anhang) wie man dieses Qualitätsmodell auch für Services anpassen könnte.

**"Subjekt authentifizieren" vs. "Subjekt authentifizieren":**
Der Begriff "Subjekt authentifizieren" wird sowohl für eine Prozesskategorie (Abbildung 8: Dunkelblau mit Farbverlauf) als auch für einen eigentlichen Prozess (Abbildung 8: Einfarbig dunkelblau) verwendet. Das führt garantiert zu Missverständnisse. Uneleganter Vorschlag: Prozesskategorie einfach "Subjekt authentifizieren und Identität föderieren" nennen. Vielleicht habt ihr kreativere Ideen; man kann auch den Prozess umbenennen… In der Folge heissen zudem die Kpt. 5.1 und 5.1.1. nicht genau gleich.

**Zusätzliche Definitionen?**
Im der Tabelle 5 des Kpt. 6.1 werden die Begriffe "Authentifizierungsstufe" (resp. "Authentisierungsstufe" – sollte dies nicht dasselbe Wort sein…?), "Client Plattform", "Kommunikationsendpunkt" und "Server Plattform" verwendet, obwohl diese nicht eingeführt wurden. Eine ad-hoc Einführung oder eine saubere Definition im Kpt. 3 fände ich sinnvoll.

**A3: Einverständnis des Subjekts**
In Tabelle 5 des Kpt. 6.1 ist das "Einverständnis des Subjekts" eine Vorbedingung. Ist dies wirklich immer zwingend notwendig? Wenn beispielsweise eine Organisationseinheit (z.B. ein Bundesamt) eine Relying Party für deinen bestimmten Service prüft und diesen für seine Mitarbeitenden freischaltet, dann macht es wenig Sinn, dass anschliessend jeder Mitarbeitende nochmals dieses Einverständnis geben muss.

**Beschreibung von 2-factor Authentication**
In der Tabelle 6 des Kpt. 6.2.1 wird 2-factor Authentication als die Kombination eines besitzabhängigen, inhärenten oder verhaltensbasierten und eines kenntnisabhängigen Authentifizierungsfaktor-Merkmals definiert. Warum muss zwingend ein kenntnisabhängiges Merkmal dabei sein? Ich empfehle zudem, diesen Satz mit den eingeführten Adjektiven aus Kpt. 3.5 zu formulieren. Dies ist dann eindeutiger.

**Qualitätsstufen analog eCH-0171**
Im Standard eCH-0171 werden im Kpt. 3.1 vier Qualitätsstufen eingeführt, die bei jedem Qualitätskriterium definiert werden. Der eCH-0170 macht etwas ähnliches, nur komplizierter, da für jedes Qualitätskriterium 2-4 Stufen definiert werden, die dann pro Prozess auf einer dieser Qualitätsstufen zugewiesen wird. Gibt es einen sinnvollen Grund, dies nicht ähnlich zu machen? Ich würde empfehlen, dass analog eCH-0171 im Kapitel 6 zuerst die Qualitätsstufen definiert werden und dann gleich pro Qualitätskriterium die Anforderungen für die Stufen 1 bis 4 (gemäss Zusammenstellung in den Tabellen 19, 20, 24, 25 und 26) definiert werden. Am Schluss ist das finale Qualitätsniveau (je Prozess und overall) analog eCH-0171 das schwächste Glied in der Kette.

**Und noch ein paar kleinere Punkte:**
- Kpt. 2.2: "[…] Bestimmung der Qualität eines Subjekts notwendig […]": Es geht hierbei wohl um die Qualität der eIdentity und nicht um das Realwelt-Element "Subjekt".
- Kpt. 4: "Subjekt föderieren": Dies sollte wohl "Identität föderieren" heissen…
- Kpt. 5.1.1.: "[…] zur Verfügung gestelltes oder unter seiner Kontrolle […]": Meiner Ansicht nach müsste hier statt ein "oder" ein "und" sein, da gemäss Kpt. 3.6 ein Authentifizierungsmittel dem Subjekt gehört und unter seiner Kontrolle ist.
- Kpt. 5.1.2: "[…] über einen sicheren Kanal": Ist dies gemäss A5 von Kpt. 6.1 nicht obsolet? Diese Formulierung hinterlässt bei mir den Eindruck, dass es in anderen Bereichen, in denen dies nicht explizit erwähnt wird, ein sicherer Kanal nicht notwendig ist.
- Kpt. 5.2.3: Tätigkeit "Der CSP übergibt dem Subjekt das Authentifizierungsmittel": Dies ist optional, da u.U. ein bereits vorhandenen eingebunden werden kann.
- Kpt. 5.3: Ich gehe davon aus, dass die anderen drei Prozesse sowie Qualitätskriterien zurzeit noch erarbeitet werden. Ist das korrekt?
- Kpt. 6.4.5: Beschreibung zu "Mit Aktivierungsprozess": Ich würde beim ersten Abschnitt "gemäss Faktor Anwesenheit und Beweismittel" und beim Abschnitt zwei "nur bei juristischen Personen, gemäss Faktor Vollmacht" ergänzen, falls ich dies korrekt verstanden habe…
- Kpt. 6.4.6: "[…] Authentifizierungsmittel beschreibt den Prozess, […]": Meiner Ansicht nach ist 'beschreibt' falsch, 'bewertet' mach wohl mehr Sinn…
- Tabelle 24 des Kpt. 7.2: Sollten die VSF nicht (1, 2, 3, 4) statt (1, 2, 2, 3) sein?

**Comment by rbuff** [comment]
Erläuterung zu Kpt. 6.4.5: Beschreibung zu "mit Aktivierungsprozess" zwecks Verständlichkeit:

Erster Abschnitt (zitiert): "Im Aktivierungsprozess wird geprüft, dass das Authentifizierungsmittel nur in den Besitz des Subjekts gelangt ist, dem es gehört". Ich würde bei diesem Abschnitt etwas in dieser Art ergänzen: "Dies wird mit hohen Stufen des Faktors Anwesenheit (PP.d, ev. auch PP.c) und des Faktors Beweismittel (IE.d, ev. auch IE.e) sichergestellt." U.U. kann diese Referenz auf diese beiden Faktoren auch bei den anderen Stufen (AD.a, AD.b und AD.c) angegeben werden...

Zweiter Abschnitt (zitiert): "Bei einer digitalen Auslieferung muss ein sicherer Kanal verwendet werden und das Subjekt (oder ein autorisierter Vertreter) muss den Empfang bestätigen." Hier würde ich bei diesem Abschnitt etwas in dieser Art ergänzen: "Vertretungen gibt es nur bei juristischen Personen und gilt nur bei einer hohen Qualitätsstufe des Faktors Vollmacht (PA.b)."

**Comment by AnnettLaube** [comment]
In der Version 0.7 des Standards eCH-0170 V2.0 werden/wurden die folgenden Punkte behandelt:
**Farbverwendung:**
Die Farbverwendung ist tatsächlich etwas verwirrend, aber es gibt ein paar Gründe:
•	Abb 1 wird in allen eCH_IAM Standards (wieder-) verwendet und kann daher nicht so leicht verändert werden
•	Abb. 5 und auch Abb 12 und 13 verwenden nun neu die Farbgebungen aus den STIAM-Standards (das Subjekt bleibt daher weiter grün)
•	Abb 4 geändert
**Flughöhe Qualitätsmodell:**
entsprechend angepasst
Der Grund für die Aufteilung des Laufzeitprozesse liegt in den Teilmodellen für das Qualitätsmodell und den Scope des Standards. Wir müssen auch nicht föderierte System (z.B. die  elektronischen Identifizierungssysteme nach eIDAs) betrachten und die kennen den Prozess „Identität föderieren nicht“.  
**Qualitätskriterien bei Prozesse:**
entsprechend angepasst
**Farbverlauf bei Prozessen**:
entsprechend angepasst 
Die **kleineren Punkte** wurden entsprechend angepasst.
Zu: Abkürzung **CP (Certification Service Provider) und CSP (Credential Service Provider)** .
Die jetzt im Standard verwendeten Abkürzungen entsp. dem internationalen Standard, aber leider nicht der üblichen Verwendung in der Schweiz. Dieser Punkte wurde von der eCH FG IAm diskutiert und akzeptiert.
Zudem wurde auch alle „Kleinigkeiten“ bzgl. Rechtschreibung und Grammatik aus dem übermittelten Word-Dokument übernommen (Kommentare sind noch offen)

**Offen** sind noch:**Terminologie**: Neue vs. umdefinierte Begriffe  & **Äquivalente Definitionen**:
Diese 2 Punkte würde ich gern im nächsten Workshop diskutieren.
Gruss,
Annett

**Comment by AnnettLaube** [comment]
War leider der falsche Issue: Antwort bezieht sich auf Issue #3.
Annett

**Comment by AnnettLaube** [comment]
Zu Kapitel 6.4.5. Übergabe Auth.mittel mit Aktivierungs-Prozess:
- Der Prozess der Festlegung der Auth.mittels ist unabhängig vom Prozess der Identifizierung der Subjekte (bei denen die Anwesenheit und die Beweismittel wichtige Kriterien sind). Es ist nicht zwingend notwendig dazu, dass das Subjekt anwesend sein muss oder bei der Übergabe nochmals ein Beweismittel vorlgen muss.

Die Sache mir Vertretung muss generell noch geklärt werden.

**Comment by AnnettLaube** [comment]
In der Version 0.7 des Standards eCH-0170 V2.0 werden/wurden die folgenden Punkte behandelt:

**Services sind ebenfalls Subjekte:**
Abgrenzung in Kap.2.2.
 
**"Subjekt authentifizieren" vs. "Subjekt authentifizieren"**:
entsprechend angepasst

**Zusätzliche Definitionen?** noch offen

**A3: Einverständnis des Subjekts**
Ist nicht zwingend notwendig -> entsp. angepasst

**Beschreibung von 2-factor Authentication**
entsprechend angepasst

**Qualitätsstufen analog eCH-0171**  (noch offen)
Das Qualitätsmodell wird nach und nach erabeitet. Im Moment gehen wir aber von 4 Stufen aus.

Und ein paar von den **kleineren Punkten**, die ich leider ablehnen musste bzw. Fragen, die ich hier beantworte. Die anderen Punkte wurden entsprechend korrigiert

Kpt. 2.2: "[…] Bestimmung der Qualität eines Subjekts notwendig […]": Es geht hierbei wohl um die Qualität der eIdentity und nicht um das Realwelt-Element "Subjekt".

- Nein, es geht wirklich um die Qualität der Authentifizierung von Subjekten (siehe auch Titel des Dokumentes)

Kpt. 5.2.3: Tätigkeit "Der CSP übergibt dem Subjekt das Authentifizierungsmittel": Dies ist optional, ...
- Für den Fall, dass das Subjekt, das einzubindende Authentifizierungsmittel bereits in seinem Besitz hat, fällt dieser Prozess und damit auch das entsprechenden Kriterium weg.
- Anpassungen im Kap. 5.2.3, 6.4.5 und 7.3

Kpt. 5.3: Ich gehe davon aus, dass die anderen drei Prozesse sowie Qualitätskriterien zurzeit noch erarbeitet werden. Ist das korrekt?

- Ja, das ist richtig, kommt in den nächsten Versionen

Kpt. 6.4.5: Beschreibung zu "Mit Aktivierungsprozess": 

- Siehe Kommentar oben

**Tabelle 24** des Kpt. 7.2: Sollten die VSF nicht (1, 2, 3, 4) statt (1, 2, 2, 3) sein?

- Nein, das ist so gewollt, für Stufe 2 gibt es 2 verschiedene Möglichkeiten, diese zu erreichen

**Comment by AnnettLaube** [comment]
In V0.8 wird der Begriff "Client Plattform" definiert. Die Begriffe "Kommunikationsendpunkt" und "Server Plattform" werden als allgemein verständlich betrachtet und daher nicht explizit im Standard definiert.
