### ISSUE TITLE
Feedback bzgl. Struktur und Lesefluss

### ISSUE THREAD

**Issue by rbuff** [iam-ictm/eCH-0170#3]
**Farbverwendung:**
Tabelle 1 erläutert die Farbverwendung im Dokument. Abbildungen 1, 4 und 5 beinhalten jedoch hellgrün und hellblau (wenn auch ein bisschen anderer Farbton), obwohl diese Konnotation nicht gemeint ist. Ich würde diese drei Abbildungen neu erzeugen und komplett auf die Farben grau, blau und grün verzichten.

**Terminologie: Neue vs. umdefinierte Begriffe**
Ich fände es sinnvoll, wenn bei der Terminologie aufgezeigt werden würde, welche Begriffe neu eingeführt werden (Kpt. 3.1, 3.4, 3.5, 3.6, 3.7, 3.12, 3.13, 3.14, 3.16, 3.17 und 3.19) und welche bzgl. Glossar von eCH-0107 (Kpt. 3.2, 3.3, 3.8, 3.9, 3.10, 3.11, 3.15 und 3.18) angepasst, resp. detaillierter definiert wurden.

**Äquivalente Definitionen:**
Die Definitionen von eIdentity (Kpt. 3.11) und Subjekt (Kpt. 3.18) sind original vom eCH-0107. Aufgrund der weiteren Begriffe (notifizierte eIdentity, Abonnent, Antragsteller und Überbringer) finde ich diese Definitionen sinnvoll. Ich würde jedoch explizit markieren, dass diese unverändert vom eCH-0107 übernommen wurden.

**Flughöhe Qualitätsmodell:**
Was ist der Grund, dass beim Qualitätsmodell zwei Prozesse "Subjekt authentifizieren" und "Identität föderieren" und zwei Prozessgruppen "Subjekt registrieren" und "Registrierung und Authentifizierung steuern" auf dieselbe Stufe gestellt werden? Ich gehe davon aus, dass es einen sinnvollen Grund gibt, dass diese ersten beiden nicht zu einem Bereich zusammengefasst wurden. Ich fände es sinnvoll, diese Begründung kurz zu erläutern, damit dies nicht zu Missverständnisse führt.

**Qualitätskriterien bei Prozesse:**
Abbildung 8 beinhaltet auch die Qualitätskriterien pro Prozess, obwohl diese nicht eingeführt wurden. Ich würde diese einfach bei dieser Grafik weglassen, da diese in Abbildung 9 erläutert werden. Ansonsten wäre ein erklärender Text im Kpt. 5 (Prozesse) hilfreich.

**Farbverlauf bei Prozessen:**
In Abbildung 9, 10 und 11 sollten die Prozesse "Subjekt authentifizieren" und "Identität föderieren" analog Abbildung 8 nicht mit einem Farbverlauf, sondern einfarbig dargestellt werden. Zudem verbessert dies auch die Lesbarkeit dieser Abbildungen.

**Und noch ein paar kleinere Punkte:**
- Bei den Credentials (Kpt. 3.9) würde ich das Synonym "Identitätsnachweis" (analog eCH-0107) noch erwähnen.
- Kpt. 5.1.1: Begriff "Ausführungszeit" sollte zu "Laufzeit" angepasst werden. Es ist so nicht falsch (da es Synonyme sind), aber diese Änderung bietet einen besseren Lesefluss, falls man nochmals die genaue Definition (Kpt. 3.16) nachlesen möchte.
- Abkürzung CP (Certification Service Provider) und CSP (Credential Service Provider) finde ich ein bisschen unglücklich. Falls dies nicht dem internationalen Standard widerspricht, fände ich CertSP statt CP (und CredSP statt CSP) intuitiver.
- Tabelle 4 in Kpt. 5.1.2: Diese Anforderungstabelle passt meiner Ansicht nach überhaupt nicht in dieses Kapitel, auch wenn sie inhaltlich sinnvoll sind. Vorschlag: Verschieben in einen Anhang.
- Kpt. 5.3.1: Die ersten beiden Tätigkeitspunkte können meinem Verständnis nach gemäss diesem Standard eCH-0170 durchgeführt werden. Ich würde dies noch explizit erwähnen, falls ich dies richtig verstanden habe…

**Comment by AnnettLaube** [comment]
siehe Issue #2 . Annett

**Comment by AnnettLaube** [comment]
Letzte offene Punkte wurden geklärt. Neue Begriffe wurden in die Terminologie/Glossar aufgenommen. Die Markierung von neuen bzw. geänderten Begriffen wurde von der FG abgelehnt.
Annett
