### ISSUE TITLE
Dritte Stufe für Faktor Nichtabstreitbarkeit (Kpt. 6.4.1.5)

### ISSUE THREAD

**Issue by rbuff** [iam-ictm/eCH-0170#4]
Beim Faktor Nichtabstreitbarkeit (Kpt. 6.4.1.5) werden zwei Stufen unterschieden: Keine Erhebung (BC.a) und Erhebung biometrischer Daten (BC.b), wobei die Stufe BC.b erst für die höchste Qualitätsstufe (IDP4) der Identifikation natürlicher Personen benötigt wird. 
Bei einem unserer Kunden wird dieser Faktor mittels Kopie eines Identitätsdokuments (ID oder Pass) berücksichtigt. Es geht dabei um den Prozess der Ausgabe von BIT-Zertifikaten mit RIO (Registration Identification Officer). [1]

Meiner Ansicht nach ist die Kopie eines Identitätsdokuments nicht so stark wie die Erhebung biometrischer Daten, da der User bei einer potentiellen Abstreitung immernoch behaupten kann, jemand anderes hätte das Dokument verwendet.
Trotzdem ist dies weit stärker als keine Erhebung (BC.a). Ich schlage vor, dass es bei diesem Faktor eine dritte, mittlere Kategorie gibt (z.B. "Kopie eines Identitätsdokuments"), das für die dritte Qualitätsstufe (IDP3) der Identifikation natürlicher Personen benötigt wird.

Wie seht ihr dies?

**Comment by AnnettLaube** [comment]
Das ist ein guter Vorschlag. Ich nehme die mittlere Stufe für die Nichtabstreitbarkeit in die Version 0.7 auf ud wir können das noch in der eCH FG diskutieren.
Annett

**Comment by AnnettLaube** [comment]
Vorschlag wurde akzeptiert. Annett
